language: android
before_install:
 - yes | sdkmanager "platforms;android-28"
 - yes | sdkmanager "build-tools;28.0.3"
 - sdkmanager --install "ndk;21.0.6113669"
 - chmod +x gradlew
script:
 - ./gradlew :DeltaUtils:clean :DeltaUtils:build
